<?php

class toba_mc_comp__2492
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'burgos_v2',
    'objeto' => 2492,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_tabla',
    'subclase' => 'dt_personas',
    'subclase_archivo' => 'datos/dt_personas.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'personas',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'burgos_v2',
    'fuente' => 'burgos_v2',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2015-06-30 07:49:15',
    'punto_montaje' => 14,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000250',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000250',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'datos_tabla',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => NULL,
    'ap_archivo' => NULL,
    'ap_punto_montaje' => 14,
    'cant_dependencias' => 0,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'tabla' => 'personas',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => 1,
    'punto_montaje' => 14,
    'ap_sub_clase' => NULL,
    'ap_sub_clase_archivo' => NULL,
    'ap_modificar_claves' => 0,
    'ap_clase' => 'ap_tabla_db_s',
    'ap_clase_archivo' => 'nucleo/componentes/persistencia/toba_ap_tabla_db_s.php',
    'tabla_ext' => NULL,
    'esquema' => NULL,
    'esquema_ext' => 'public',
  ),
  '_info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1001,
      'columna' => 'id',
      'tipo' => 'E',
      'pk' => 1,
      'secuencia' => 'seq_personas',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    1 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1002,
      'columna' => 'id_genero',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    2 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1003,
      'columna' => 'id_estado_civil',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    3 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1004,
      'columna' => 'id_documento_tipo',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    4 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1005,
      'columna' => 'id_pais_nacimiento',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    5 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1006,
      'columna' => 'id_distrito',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    6 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1007,
      'columna' => 'id_localidad',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    7 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1008,
      'columna' => 'id_nivel_instruccion',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    8 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1009,
      'columna' => 'id_barrio',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    9 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1010,
      'columna' => 'documento_nro',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    10 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1011,
      'columna' => 'apellido',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 15,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    11 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1012,
      'columna' => 'nombre',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 15,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    12 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1013,
      'columna' => 'fecha_nacimiento',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    13 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1014,
      'columna' => 'lugar_nacimiento',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 40,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    14 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1015,
      'columna' => 'nacionalidad',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 30,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    15 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1016,
      'columna' => 'domicilio_real',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 60,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    16 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1017,
      'columna' => 'propietario_inmueble',
      'tipo' => 'L',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    17 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1018,
      'columna' => 'telefono',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 50,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    18 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1019,
      'columna' => 'mail',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 50,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    19 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1020,
      'columna' => 'ocupacion',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 50,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    20 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1021,
      'columna' => 'necesidades_especiales',
      'tipo' => 'L',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    21 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1022,
      'columna' => 'beneficios_sociales',
      'tipo' => 'L',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    22 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1023,
      'columna' => 'redes_sociales_institucionales',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 300,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    23 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1037,
      'columna' => 'titulo',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 20,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'personas',
    ),
    24 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2492,
      'col_id' => 1084,
      'columna' => 'antecedente_violencia',
      'tipo' => 'L',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'personas',
    ),
  ),
  '_info_externas' => 
  array (
  ),
  '_info_externas_col' => 
  array (
  ),
  '_info_valores_unicos' => 
  array (
  ),
  '_info_fks' => 
  array (
  ),
);
	}

}

?>