<?php

class toba_mc_comp__16
{
	static function get_metadatos()
	{
		return array (
  'molde' => 
  array (
    'proyecto' => 'burgos_v2',
    'molde' => 16,
    'operacion_tipo' => 10,
    'nombre' => 'Clasificadores',
    'item' => '3483',
    'carpeta_archivos' => 'clasificadores',
    'prefijo_clases' => '_clasificadores',
    'fuente' => 'burgos_v2',
    'clase' => 'toba_asistente_abms',
  ),
  'molde_abms' => 
  array (
    'proyecto' => 'burgos_v2',
    'molde' => 16,
    'tabla' => 'clasificadores',
    'gen_usa_filtro' => 1,
    'gen_separar_pantallas' => 1,
    'cuadro_eof' => NULL,
    'cuadro_id' => 'id',
    'filtro_comprobar_parametros' => 0,
    'cuadro_forzar_filtro' => 0,
    'cuadro_eliminar_filas' => 0,
    'cuadro_carga_origen' => 'datos_tabla',
    'cuadro_carga_sql' => 'SELECT
	t_c.id,
	t_a.nombre as id_ambito_nombre,
	t_tc.nombre as id_tipo1_nombre,
	t_tc1.nombre as id_tipo2_nombre,
	t_tc2.nombre as id_tipo3_nombre,
	t_c.violencia,
	t_tv.nombre as id_tipov1_nombre,
	t_tv3.nombre as id_tipov2_nombre,
	t_tv4.nombre as id_tipov3_nombre
FROM
	clasificadores as t_c	LEFT OUTER JOIN ambitos as t_a ON (t_c.id_ambito = t_a.id)
	LEFT OUTER JOIN tipos_casos as t_tc ON (t_c.id_tipo1 = t_tc.id)
	LEFT OUTER JOIN tipos_casos as t_tc1 ON (t_c.id_tipo2 = t_tc1.id)
	LEFT OUTER JOIN tipos_casos as t_tc2 ON (t_c.id_tipo3 = t_tc2.id)
	LEFT OUTER JOIN tipos_violencias as t_tv ON (t_c.id_tipov1 = t_tv.id)
	LEFT OUTER JOIN tipos_violencias as t_tv3 ON (t_c.id_tipov2 = t_tv3.id)
	LEFT OUTER JOIN tipos_violencias as t_tv4 ON (t_c.id_tipov3 = t_tv4.id)',
    'cuadro_carga_php_include' => NULL,
    'cuadro_carga_php_clase' => NULL,
    'cuadro_carga_php_metodo' => NULL,
    'datos_tabla_validacion' => NULL,
    'apdb_pre' => NULL,
  ),
  'molde_abms_fila' => 
  array (
    0 => 
    array (
      'proyecto' => 'burgos_v2',
      'molde' => 16,
      'fila' => 122,
      'orden' => '1',
      'columna' => 'id',
      'etiqueta' => 'Id',
      'en_cuadro' => 0,
      'en_form' => 0,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 0,
      'cuadro_formato' => 7,
      'dt_tipo_dato' => 'E',
      'dt_largo' => NULL,
      'dt_secuencia' => 'seq_clasificadores',
      'dt_pk' => 1,
      'elemento_formulario' => 'ef_editable_numero',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    1 => 
    array (
      'proyecto' => 'burgos_v2',
      'molde' => 16,
      'fila' => 123,
      'orden' => '2',
      'columna' => 'id_ambito',
      'etiqueta' => 'Id Ambito',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 1,
      'filtro_operador' => '=',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 1,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id, nombre FROM ambitos ORDER BY nombre',
      'ef_carga_tabla' => 'ambitos',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id',
      'ef_carga_col_desc' => 'nombre',
    ),
    2 => 
    array (
      'proyecto' => 'burgos_v2',
      'molde' => 16,
      'fila' => 124,
      'orden' => '3',
      'columna' => 'id_tipo1',
      'etiqueta' => 'Id Tipo1',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id, nombre FROM tipos_casos ORDER BY nombre',
      'ef_carga_tabla' => 'tipos_casos',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id',
      'ef_carga_col_desc' => 'nombre',
    ),
    3 => 
    array (
      'proyecto' => 'burgos_v2',
      'molde' => 16,
      'fila' => 125,
      'orden' => '4',
      'columna' => 'id_tipo2',
      'etiqueta' => 'Id Tipo2',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id, nombre FROM tipos_casos ORDER BY nombre',
      'ef_carga_tabla' => 'tipos_casos',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id',
      'ef_carga_col_desc' => 'nombre',
    ),
    4 => 
    array (
      'proyecto' => 'burgos_v2',
      'molde' => 16,
      'fila' => 126,
      'orden' => '5',
      'columna' => 'id_tipo3',
      'etiqueta' => 'Id Tipo3',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id, nombre FROM tipos_casos ORDER BY nombre',
      'ef_carga_tabla' => 'tipos_casos',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id',
      'ef_carga_col_desc' => 'nombre',
    ),
    5 => 
    array (
      'proyecto' => 'burgos_v2',
      'molde' => 16,
      'fila' => 127,
      'orden' => '6',
      'columna' => 'violencia',
      'etiqueta' => 'Violencia',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 1,
      'filtro_operador' => '=',
      'cuadro_estilo' => 7,
      'cuadro_formato' => 13,
      'dt_tipo_dato' => 'L',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_checkbox',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => NULL,
      'ef_carga_sql' => NULL,
      'ef_carga_tabla' => NULL,
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => NULL,
      'ef_carga_col_desc' => NULL,
    ),
    6 => 
    array (
      'proyecto' => 'burgos_v2',
      'molde' => 16,
      'fila' => 128,
      'orden' => '7',
      'columna' => 'id_tipov1',
      'etiqueta' => 'Id Tipov1',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id, nombre FROM tipos_violencias ORDER BY nombre',
      'ef_carga_tabla' => 'tipos_violencias',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id',
      'ef_carga_col_desc' => 'nombre',
    ),
    7 => 
    array (
      'proyecto' => 'burgos_v2',
      'molde' => 16,
      'fila' => 129,
      'orden' => '8',
      'columna' => 'id_tipov2',
      'etiqueta' => 'Id Tipov2',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id, nombre FROM tipos_violencias ORDER BY nombre',
      'ef_carga_tabla' => 'tipos_violencias',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id',
      'ef_carga_col_desc' => 'nombre',
    ),
    8 => 
    array (
      'proyecto' => 'burgos_v2',
      'molde' => 16,
      'fila' => 130,
      'orden' => '9',
      'columna' => 'id_tipov3',
      'etiqueta' => 'Id Tipov3',
      'en_cuadro' => 1,
      'en_form' => 1,
      'en_filtro' => 0,
      'filtro_operador' => '=',
      'cuadro_estilo' => 4,
      'cuadro_formato' => 1,
      'dt_tipo_dato' => 'C',
      'dt_largo' => NULL,
      'dt_secuencia' => '',
      'dt_pk' => 0,
      'elemento_formulario' => 'ef_combo',
      'ef_desactivar_modificacion' => NULL,
      'ef_procesar_javascript' => NULL,
      'ef_obligatorio' => 0,
      'ef_carga_origen' => 'datos_tabla',
      'ef_carga_sql' => 'SELECT id, nombre FROM tipos_violencias ORDER BY nombre',
      'ef_carga_tabla' => 'tipos_violencias',
      'ef_carga_php_include' => NULL,
      'ef_carga_php_clase' => NULL,
      'ef_carga_php_metodo' => NULL,
      'ef_carga_col_clave' => 'id',
      'ef_carga_col_desc' => 'nombre',
    ),
  ),
);
	}

}

?>