<?php

class toba_mc_comp__2547
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'burgos_v2',
    'objeto' => 2547,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_tabla',
    'subclase' => NULL,
    'subclase_archivo' => NULL,
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'DT - oficios',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'burgos_v2',
    'fuente' => 'burgos_v2',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2015-07-23 12:02:28',
    'punto_montaje' => 14,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000250',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000250',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'datos_tabla',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => NULL,
    'ap_archivo' => NULL,
    'ap_punto_montaje' => 14,
    'cant_dependencias' => 0,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'tabla' => 'oficios',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => 1,
    'punto_montaje' => 14,
    'ap_sub_clase' => NULL,
    'ap_sub_clase_archivo' => NULL,
    'ap_modificar_claves' => 0,
    'ap_clase' => 'ap_tabla_db_s',
    'ap_clase_archivo' => 'nucleo/componentes/persistencia/toba_ap_tabla_db_s.php',
    'tabla_ext' => NULL,
    'esquema' => NULL,
    'esquema_ext' => 'public',
  ),
  '_info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1087,
      'columna' => 'id',
      'tipo' => 'E',
      'pk' => 1,
      'secuencia' => 'oficios_id_seq',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    1 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1088,
      'columna' => 'nro_emision',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 30,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    2 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1089,
      'columna' => 'nro_recepcion',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 30,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    3 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1090,
      'columna' => 'fecha_emision',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    4 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1091,
      'columna' => 'fecha_recepcion',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    5 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1092,
      'columna' => 'destino',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 50,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    6 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1093,
      'columna' => 'persona',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 50,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    7 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1094,
      'columna' => 'tiempo_respuesta',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    8 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1095,
      'columna' => 'contestado',
      'tipo' => 'L',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    9 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1096,
      'columna' => 'fecha_respuesta',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    10 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1097,
      'columna' => 'habilitado',
      'tipo' => 'L',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
    11 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2547,
      'col_id' => 1098,
      'columna' => 'id_expediente',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'oficios',
    ),
  ),
  '_info_externas' => 
  array (
  ),
  '_info_externas_col' => 
  array (
  ),
  '_info_valores_unicos' => 
  array (
  ),
  '_info_fks' => 
  array (
  ),
);
	}

}

?>