<?php

class toba_mc_comp__2517
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'burgos_v2',
    'objeto' => 2517,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_ci',
    'subclase' => 'ci_editor_exp',
    'subclase_archivo' => 'expedientes/ci_editor_exp.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'Gestionar Expediente - editor',
    'titulo' => NULL,
    'colapsable' => 0,
    'descripcion' => NULL,
    'fuente_proyecto' => NULL,
    'fuente' => NULL,
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2015-07-06 12:58:04',
    'punto_montaje' => 14,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000249',
    'clase_archivo' => 'nucleo/componentes/interface/toba_ci.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000249',
    'clase_icono' => 'objetos/multi_etapa.gif',
    'clase_descripcion_corta' => 'ci',
    'clase_instanciador_proyecto' => 'toba_editor',
    'clase_instanciador_item' => '1642',
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => NULL,
    'ap_archivo' => NULL,
    'ap_punto_montaje' => NULL,
    'cant_dependencias' => 6,
    'posicion_botonera' => 'abajo',
  ),
  '_info_eventos' => 
  array (
  ),
  '_info_puntos_control' => 
  array (
  ),
  '_info_ci' => 
  array (
    'ev_procesar_etiq' => NULL,
    'ev_cancelar_etiq' => NULL,
    'objetos' => NULL,
    'ancho' => '100%',
    'alto' => NULL,
    'posicion_botonera' => NULL,
    'tipo_navegacion' => 'tab_h',
    'con_toc' => 0,
    'botonera_barra_item' => 0,
  ),
  '_info_ci_me_pantalla' => 
  array (
    0 => 
    array (
      'pantalla' => 1254,
      'identificador' => 'pant_expedientes',
      'etiqueta' => 'Expedientes',
      'descripcion' => NULL,
      'tip' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => NULL,
      'objetos' => NULL,
      'eventos' => NULL,
      'orden' => 1,
      'punto_montaje' => NULL,
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'template' => NULL,
      'template_impresion' => NULL,
    ),
    1 => 
    array (
      'pantalla' => 1255,
      'identificador' => 'pant_profesionales',
      'etiqueta' => 'Profesionales',
      'descripcion' => NULL,
      'tip' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => NULL,
      'objetos' => NULL,
      'eventos' => NULL,
      'orden' => 2,
      'punto_montaje' => NULL,
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'template' => NULL,
      'template_impresion' => NULL,
    ),
    2 => 
    array (
      'pantalla' => 1256,
      'identificador' => 'pant_personas',
      'etiqueta' => 'Personas',
      'descripcion' => NULL,
      'tip' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => NULL,
      'objetos' => NULL,
      'eventos' => NULL,
      'orden' => 3,
      'punto_montaje' => NULL,
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'template' => NULL,
      'template_impresion' => NULL,
    ),
    3 => 
    array (
      'pantalla' => 1265,
      'identificador' => 'pant_intervenciones',
      'etiqueta' => 'Intervenciones',
      'descripcion' => NULL,
      'tip' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => NULL,
      'objetos' => NULL,
      'eventos' => NULL,
      'orden' => 4,
      'punto_montaje' => NULL,
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'template' => NULL,
      'template_impresion' => NULL,
    ),
    4 => 
    array (
      'pantalla' => 1267,
      'identificador' => 'pant_oficios',
      'etiqueta' => 'Oficios',
      'descripcion' => NULL,
      'tip' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => NULL,
      'objetos' => NULL,
      'eventos' => NULL,
      'orden' => 5,
      'punto_montaje' => NULL,
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'template' => NULL,
      'template_impresion' => NULL,
    ),
    5 => 
    array (
      'pantalla' => 1272,
      'identificador' => 'pant_derivaciones',
      'etiqueta' => 'Instiuciones y Redes Sociales',
      'descripcion' => NULL,
      'tip' => NULL,
      'imagen_recurso_origen' => 'apex',
      'imagen' => NULL,
      'objetos' => NULL,
      'eventos' => NULL,
      'orden' => 6,
      'punto_montaje' => NULL,
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'template' => NULL,
      'template_impresion' => NULL,
    ),
  ),
  '_info_obj_pantalla' => 
  array (
    0 => 
    array (
      'pantalla' => 1254,
      'proyecto' => 'burgos_v2',
      'objeto_ci' => 2517,
      'dep_id' => 1362,
      'orden' => 0,
      'identificador_pantalla' => 'pant_expedientes',
      'identificador_dep' => 'frm_expediente',
    ),
    1 => 
    array (
      'pantalla' => 1255,
      'proyecto' => 'burgos_v2',
      'objeto_ci' => 2517,
      'dep_id' => 1381,
      'orden' => 0,
      'identificador_pantalla' => 'pant_profesionales',
      'identificador_dep' => 'ml_profesionales',
    ),
    2 => 
    array (
      'pantalla' => 1256,
      'proyecto' => 'burgos_v2',
      'objeto_ci' => 2517,
      'dep_id' => 1387,
      'orden' => 0,
      'identificador_pantalla' => 'pant_personas',
      'identificador_dep' => 'ml_personas',
    ),
    3 => 
    array (
      'pantalla' => 1265,
      'proyecto' => 'burgos_v2',
      'objeto_ci' => 2517,
      'dep_id' => 1388,
      'orden' => 0,
      'identificador_pantalla' => 'pant_intervenciones',
      'identificador_dep' => 'ml_intevenciones',
    ),
    4 => 
    array (
      'pantalla' => 1267,
      'proyecto' => 'burgos_v2',
      'objeto_ci' => 2517,
      'dep_id' => 1392,
      'orden' => 0,
      'identificador_pantalla' => 'pant_oficios',
      'identificador_dep' => 'ml_oficios',
    ),
    5 => 
    array (
      'pantalla' => 1272,
      'proyecto' => 'burgos_v2',
      'objeto_ci' => 2517,
      'dep_id' => 1414,
      'orden' => 0,
      'identificador_pantalla' => 'pant_derivaciones',
      'identificador_dep' => 'ml_derivaciones',
    ),
  ),
  '_info_evt_pantalla' => 
  array (
  ),
  '_info_dependencias' => 
  array (
    0 => 
    array (
      'identificador' => 'frm_expediente',
      'proyecto' => 'burgos_v2',
      'objeto' => 2518,
      'clase' => 'toba_ei_formulario',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ei_formulario.php',
      'subclase' => 'frm_expediente',
      'subclase_archivo' => 'expedientes/edicion/frm_expediente.php',
      'fuente' => 'burgos_v2',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    1 => 
    array (
      'identificador' => 'ml_derivaciones',
      'proyecto' => 'burgos_v2',
      'objeto' => 2568,
      'clase' => 'toba_ei_formulario_ml',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ei_formulario_ml.php',
      'subclase' => 'ml_derivaciones',
      'subclase_archivo' => 'expedientes/edicion/ml_derivaciones.php',
      'fuente' => 'burgos_v2',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    2 => 
    array (
      'identificador' => 'ml_intevenciones',
      'proyecto' => 'burgos_v2',
      'objeto' => 2543,
      'clase' => 'toba_ei_formulario_ml',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ei_formulario_ml.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'burgos_v2',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    3 => 
    array (
      'identificador' => 'ml_oficios',
      'proyecto' => 'burgos_v2',
      'objeto' => 2548,
      'clase' => 'toba_ei_formulario_ml',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ei_formulario_ml.php',
      'subclase' => 'ml_oficios',
      'subclase_archivo' => 'expedientes/edicion/ml_oficios.php',
      'fuente' => 'burgos_v2',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    4 => 
    array (
      'identificador' => 'ml_personas',
      'proyecto' => 'burgos_v2',
      'objeto' => 2542,
      'clase' => 'toba_ei_formulario_ml',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ei_formulario_ml.php',
      'subclase' => 'ml_personas',
      'subclase_archivo' => 'expedientes/edicion/ml_personas.php',
      'fuente' => 'burgos_v2',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
    5 => 
    array (
      'identificador' => 'ml_profesionales',
      'proyecto' => 'burgos_v2',
      'objeto' => 2536,
      'clase' => 'toba_ei_formulario_ml',
      'clase_archivo' => 'nucleo/componentes/interface/toba_ei_formulario_ml.php',
      'subclase' => NULL,
      'subclase_archivo' => NULL,
      'fuente' => 'burgos_v2',
      'parametros_a' => NULL,
      'parametros_b' => NULL,
    ),
  ),
);
	}

}

?>