<?php

class toba_mc_comp__2431
{
	static function get_metadatos()
	{
		return array (
  '_info' => 
  array (
    'proyecto' => 'burgos_v2',
    'objeto' => 2431,
    'anterior' => NULL,
    'identificador' => NULL,
    'reflexivo' => NULL,
    'clase_proyecto' => 'toba',
    'clase' => 'toba_datos_tabla',
    'subclase' => 'dt_expedientes',
    'subclase_archivo' => 'datos/dt_expedientes.php',
    'objeto_categoria_proyecto' => NULL,
    'objeto_categoria' => NULL,
    'nombre' => 'expedientes',
    'titulo' => NULL,
    'colapsable' => NULL,
    'descripcion' => NULL,
    'fuente_proyecto' => 'burgos_v2',
    'fuente' => 'burgos_v2',
    'solicitud_registrar' => NULL,
    'solicitud_obj_obs_tipo' => NULL,
    'solicitud_obj_observacion' => NULL,
    'parametro_a' => NULL,
    'parametro_b' => NULL,
    'parametro_c' => NULL,
    'parametro_d' => NULL,
    'parametro_e' => NULL,
    'parametro_f' => NULL,
    'usuario' => NULL,
    'creacion' => '2015-03-31 17:18:46',
    'punto_montaje' => 14,
    'clase_editor_proyecto' => 'toba_editor',
    'clase_editor_item' => '1000250',
    'clase_archivo' => 'nucleo/componentes/persistencia/toba_datos_tabla.php',
    'clase_vinculos' => NULL,
    'clase_editor' => '1000250',
    'clase_icono' => 'objetos/datos_tabla.gif',
    'clase_descripcion_corta' => 'datos_tabla',
    'clase_instanciador_proyecto' => NULL,
    'clase_instanciador_item' => NULL,
    'objeto_existe_ayuda' => NULL,
    'ap_clase' => NULL,
    'ap_archivo' => NULL,
    'ap_punto_montaje' => 14,
    'cant_dependencias' => 0,
    'posicion_botonera' => NULL,
  ),
  '_info_estructura' => 
  array (
    'tabla' => 'expedientes',
    'alias' => NULL,
    'min_registros' => NULL,
    'max_registros' => NULL,
    'ap' => 1,
    'punto_montaje' => 14,
    'ap_sub_clase' => NULL,
    'ap_sub_clase_archivo' => NULL,
    'ap_modificar_claves' => 0,
    'ap_clase' => 'ap_tabla_db_s',
    'ap_clase_archivo' => 'nucleo/componentes/persistencia/toba_ap_tabla_db_s.php',
    'tabla_ext' => NULL,
    'esquema' => NULL,
    'esquema_ext' => 'public',
  ),
  '_info_columnas' => 
  array (
    0 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1042,
      'columna' => 'id',
      'tipo' => 'E',
      'pk' => 1,
      'secuencia' => 'seq_expedientes',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    1 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1043,
      'columna' => 'id_procedencia',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    2 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1044,
      'columna' => 'id_tipogestion',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    3 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1045,
      'columna' => 'id_clasificador',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    4 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1046,
      'columna' => 'id_estado_expediente',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    5 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1047,
      'columna' => 'fecha_presentacion',
      'tipo' => 'T',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    6 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1048,
      'columna' => 'fecha_ultimo_mov',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    7 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1049,
      'columna' => 'id_responsable_ingreso',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    8 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1050,
      'columna' => 'numero',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => NULL,
      'largo' => 50,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    9 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1051,
      'columna' => 'denuncia_policial',
      'tipo' => 'L',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    10 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1052,
      'columna' => 'lugar_denuncia',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 30,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    11 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1053,
      'columna' => 'fecha_denuncia',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 30,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    12 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1054,
      'columna' => 'persona_denuncia',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    13 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1055,
      'columna' => 'lugar_hecho_denuncia',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 50,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    14 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1056,
      'columna' => 'ultimo_episodio_denuncia',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    15 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1057,
      'columna' => 'encuadre_legal',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    16 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1058,
      'columna' => 'aplicacion_ley',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 50,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    17 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1059,
      'columna' => 'id_estado_relatoria',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    18 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1060,
      'columna' => 'fecha_entrada',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    19 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1061,
      'columna' => 'fecha_salida',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    20 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1062,
      'columna' => 'fecha_cierre',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    21 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1063,
      'columna' => 'fecha_archivo',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    22 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1064,
      'columna' => 'procedencia',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 30,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    23 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1065,
      'columna' => 'id_institucion',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    24 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1066,
      'columna' => 'origen_presentacion',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 35,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    25 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1067,
      'columna' => 'motivo_consuta',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    26 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1068,
      'columna' => 'observaciones',
      'tipo' => 'X',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    27 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1069,
      'columna' => 'organismo',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 30,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    28 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1070,
      'columna' => 'dependencia_org',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 30,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    29 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1071,
      'columna' => 'lugar',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 20,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    30 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1072,
      'columna' => 'tipo_atencion',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 30,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    31 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1073,
      'columna' => 'id_ambito',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    32 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1074,
      'columna' => 'nomeclador_1',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    33 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1075,
      'columna' => 'nomeclador_2',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    34 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1076,
      'columna' => 'nomeclador_3',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    35 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1077,
      'columna' => 'violencia_1',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    36 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1078,
      'columna' => 'violencia_2',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    37 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1079,
      'columna' => 'violencia_3',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    38 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1083,
      'columna' => 'fecha_derivacion',
      'tipo' => 'T',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    39 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1086,
      'columna' => 'hubo_violencia',
      'tipo' => 'L',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    40 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1115,
      'columna' => 'estado',
      'tipo' => 'E',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 1,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    41 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1116,
      'columna' => 'fecha_oficio',
      'tipo' => 'F',
      'pk' => 0,
      'secuencia' => '',
      'largo' => NULL,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
    42 => 
    array (
      'objeto_proyecto' => 'burgos_v2',
      'objeto' => 2431,
      'col_id' => 1117,
      'columna' => 'nro_expediente_judicial',
      'tipo' => 'C',
      'pk' => 0,
      'secuencia' => '',
      'largo' => 30,
      'no_nulo' => NULL,
      'no_nulo_db' => 0,
      'externa' => 0,
      'tabla' => 'expedientes',
    ),
  ),
  '_info_externas' => 
  array (
  ),
  '_info_externas_col' => 
  array (
  ),
  '_info_valores_unicos' => 
  array (
  ),
  '_info_fks' => 
  array (
  ),
);
	}

}

?>